### ISSUE TITLE
One-hot encoding

### ISSUE THREAD

**Issue by ck37** [rafaelvalle/MDI#1]
Not sure that ya'll are using "one-hot encoding" correctly. Usually it refers to converting a categorical variable to a series of indicators in which only a single indicator is set to 1 for a given observation. In this case, the usage seems to be referring to simply creating an indicator variable for missingness, which is a simpler concept. I also saw this usage in the previous stat 215a repo back in December so figured I'd make a quick note.

**Comment by rafaelvalle** [comment]
Thank you, ck37. 
Mistakenly I replicated methods one_hot and binarize_data!

**Comment by rafaelvalle** [comment]
Hi Chris,
Thank you for calling attention to this!

The data must be in the correct format to output the correct result, otherwise the behavior you mentioned will occur.

Rows as observations and columns as features.

``` python
import numpy as np
import missing_data_imputation as mdi

imp = mdi.Imputer()
missing_data_cond = lambda x : x == '?'
data = np.array([['a'], ['a'], ['a'], ['b'], ['b'], ['?']])
data_wrong = np.array([['a', 'a', 'a', 'b', 'b', '?']])
```

Correct formatting

``` python
imp.binarize_data(data, (0,))
Out[1]:
array([['-1', '1', '-1'],
       ['-1', '1', '-1'],
       ['-1', '1', '-1'],
       ['-1', '-1', '1'],
       ['-1', '-1', '1'],
       ['1', '-1', '-1']],
      dtype='|S21')
```

Wrong formatting

``` python
imp.binarize_data(data_wrong, (0,))
Out[2]:
array([['a', 'a', 'b', 'b', '?', '1']],
      dtype='|S21')
```
